/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118422-g1fbe9deee3-20250204"
#endif /* AVUTIL_FFVERSION_H */
