/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-117656-gca71b0b807-20241026"
#endif /* AVUTIL_FFVERSION_H */
