# Generated by Django 5.0.7 on 2024-09-14 00:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pptx_file', models.FileField(upload_to='presento/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('process_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
    ]
