# Generated by Django 5.1.1 on 2024-10-17 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presento', '0002_presento_process_percentage_presento_voice_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presento',
            old_name='voice_model',
            new_name='model_choice',
        ),
    ]
