# Generated by Django 5.1.1 on 2024-10-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presento', '0003_rename_voice_model_presento_model_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='presento',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
